### ISSUE TITLE
Upload existing code

### ISSUE THREAD

**Issue by emilljungberg** [SwedishNational7TMRI/7T_BIDS_organiser#1]
Structure and upload code from Finn's 7T project.

**Comment by finnlennartsson** [comment]
@emilljungberg 
Can you make it possible for me to push to the repo?
![image](https://user-images.githubusercontent.com/20419258/201166296-a968e97c-dab0-4905-ba2c-5885a2e05b6d.png)

**Comment by emilljungberg** [comment]
Sorted! I've made you, Theo and Nicola admins of the repo as well. Others will have to do pull requests.

**Comment by finnlennartsson** [comment]
Code is now uploaded.
