### ISSUE TITLE
Update script to take any a user-specified heuristic-file

### ISSUE THREAD

**Issue by finnlennartsson** [SwedishNational7TMRI/7T_BIDS_organiser#2]
I.e. make an optional input argument where a default can be specified

https://github.com/SwedishNational7TMRI/7T_BIDS_organiser/blob/c78425f4f03ae2fd3d3497e0a0987d2160a2a21f/DcmSourcedata_to_NiftiRawdata.sh#L74

**Comment by finnlennartsson** [comment]
Implemented this new code in a new branch called "test".

@TheoRum can you check out the new branch "test" and see if the new version of the "DcmSourcedata_to_NiftiRawdata.sh" if it works with your data? I.e. if you can give it an input heuristic file?

After this the "test" branch can be merged with "main"

**Comment by emilljungberg** [comment]
I've just made a major update to the code which incorporates that. Have a look at 2fe2d58. I haven't done the pull request into `main` yet as I think it needs more testing.
