### ISSUE TITLE
Strunta i study_key?

### ISSUE THREAD

**Issue by finnlennartsson** [SwedishNational7TMRI/7T_BIDS_organiser#4]
Det är bättre att strunta helt i "study_key" som input. Det var bara en grej jag gjorde för att snabbt kunna processa flera dataset som kommit via MIPP (dom får ju separat running number där). Tror det är förvirrande bara, och kommandot som tar ut MIPP och sID kräver ju att tsv.filen har rätt format (även om det ju ligger i definitionen av en tsv-fil),
https://github.com/SwedishNational7TMRI/7T_BIDS_organiser/blob/a0ef9426a7ad63d4fcc6b74b7feebc09ba688954/shell/7Tbids_sort_dicoms.sh#L78

Istället tar man som input den aktuella katalog som ens DICOMs ligger, dvs `$dicomdir/${folder_id}` i kommandot https://github.com/SwedishNational7TMRI/7T_BIDS_organiser/blob/a0ef9426a7ad63d4fcc6b74b7feebc09ba688954/shell/7Tbids_sort_dicoms.sh#L102
som helt enkelt får vara DICOMDIR i `DICOMDIR=<my_dicom_dir>="$dicomdir/${folder_id}`

Behåller study_ID (=sID) för att bestämma hur dom skall sorteras i sourcedata/sub-$sID och däri med filnamn.

**Comment by emilljungberg** [comment]
No longer used.
