### ISSUE TITLE
fix BIDS rawdata folder

### ISSUE THREAD

**Issue by finnlennartsson** [SwedishNational7TMRI/7T_BIDS_organiser#5]

**Comment by emilljungberg** [comment]
I will sort this out asap.

**Comment by finnlennartsson** [comment]
In Axel's code, he used a new BIDS rawdata folder,  `fixed_rawdata`, for the corrected `rawdata` folder. However, according to the BIDS standard, the `rawdata` folder should be the BIDS data folder and any corrections can be done in this directly (this is what e.g. dHCP does), or in line with Axel's coding, if the `rawdata` folder is first renamed `rawdata_non_BIDS`, then everything is "fixed" into the `rawdata` folder. 

The `rawdata_non_BIDS` folder can as the last thing be deleted (or as an option saved for debugging).

**Comment by emilljungberg** [comment]
I agree. That makes more sense. I'll do the easiest solution for now, renaming the folders afterwards.

**Comment by emilljungberg** [comment]
This has now been changed such that we used `temp_rawdata` pre-fixes and then `rawdata`. This is reflected in the config file but should be cleaned up later.
