### ISSUE TITLE
Implementation of sMRI pipeline: AVOID passing on skull-stripped output from cat12

### ISSUE THREAD

**Issue by finnlennartsson** [SwedishNational7TMRI/7T_BIDS_organiser#6]
[Axel's pipeline](https://github.com/finnlennartsson/7T049_CVI/blob/a6d3840deb52cb302d6b1ac0861c15d01c6a4fd1/bids/pipeline.py) is a replica of the Knapen Lab's [anatomical workflows](https://github.com/tknapen/tknapen.github.io/wiki/Anatomical-workflows).

There is an important difference though. In the original pipeline, the output should be a denoised T1w image (both background and internal noise removal). Axel's pipeline is outputting a denoised but **skull-stripped** T1w image. 

The recommendation from fMRIprep is not to use a skull-stripped image. See point in [FAQ](https://fmriprep.org/en/22.0.2/faq.html#what-if-i-find-some-images-have-undergone-some-pre-processing-already-e-g-my-t1w-image-is-already-skull-stripped) and relevant neurostars issues related to this (see links in FAQ entry).

**Comment by emilljungberg** [comment]
This has been updated now in 7b0829e. The `cat12` command now runs as it should but the output files stays in the cat12 folder. Todo:

1. Move files to raw data
`.../cat12/sub-XXX_desc-pymp2ragecat12_T1w.nii.gz` 
to 
`raw data/sub<X>/anat/sub-XXX_rec-pymp2rageCat12_UNIT1.nii.gz`
Note how we have swapped from `desc` to `rec` which stands for reconstruction. 

2. Copy over the corresponding .json sidecar.
3. This new file must be added into `studydir/rawdata/sub-XXX/sub-XXX_scans.tsv`.

**Comment by emilljungberg** [comment]
This has now been completed with 6ceef5d2cb6f1fb6a0363952112050454dd0d62b. Axel has implemented that the new file gets copied to `rawdata/sub<X>/anat/sub-XXX_rec-pymp2rageCat12_UNIT1.nii.gz`. The json sidecar is also included and the new file is added to the scans.tsv file.
